### ISSUE TITLE
TypeError: list indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by Darkstone245** [ppravatto/28C256#1]
When writing to the Chip via a binary file, its says that theres a TypeError in line 189: TypeError: list indices must be integers or slices, not tuple. 
I tried to fix it but i didnt really understand too much of the code. Please help

**Comment by ppravatto** [comment]
Thank you for pointing out the bug! There is indeed a typo in the code at line 189 where there is a comma `,` in place of the slicing operator `:`.

By changing the line to `chunk = data[i*MAX_CHUNK_SIZE : (i+1)*MAX_CHUNK_SIZE]` the bug should be fixed. The modified code is available in the [`1-typeerror-list-indices-must-be-integers-or-slices-not-tuple`](https://github.com/ppravatto/28C256/compare/1-typeerror-list-indices-must-be-integers-or-slices-not-tuple) branch. Let me know if this solves the issue.

**Comment by ppravatto** [comment]
I have tested the program with a binary file generated with the script:

```python
rom = bytearray([0xea] * 32768)

with open("rom.bin", "wb") as file:
    file.write(rom)
```

and the program seems to work correctly now. Bug-fix merged into the main branch and the issue closed.
